FORMAT: 1A
HOST: http://lifebelt.apiblueprint.org/

# lifebelt

Lifebelt is teachers's lifebelt to simplify 
publish, share and review homeworks and exams. Also helps students,
giving them easy way to follow and be inform about new assignments, receiving
instant review where is possible.

# Group Courses

# Courses [/courses]

## Get all courses [GET]
+ Response 200

## Create a new course [POST]
+ Response 201

# Course [/courses/{course_id}]

## Get specific course by id [GET]
+ Response 200 (application/json)
        
        {
            "id": 123,
            "initials": "PO",
            "fullname": "Програмно осигуряване",
            "description": "Запознаване със структури от данни и езикът 'С'",
            "year": 2016
        }

## Edit existing course with given id [PUT]
+ Response 200

## Delete existing course by id [DELETE]
+ Response 204

# Group Course Assignments

# Assignments [/courses/{course_id}/assignments]

## Get all course assignments [GET]
+ Response 200

## Create new course assignment [POST]
+ Response 201

# Assignment [/courses/{course_id}/assignments/{ass_id}]

## Get specific course assignment by id [GET]
+ Response 200 (application/json)
        
        {
            "id": 123,
            "name": "Програмно осигуряване",
            "description": "Запознаване със структури от данни и езикът 'С'",
            "type": "exam|homework",
            "start": "2012-04-23T18:25:43.511Z",
            "end": "2012-04-23T18:25:43.511Z"
        }

## Update existing course assignment [PUT]
+ Response 200

## Delete existing course assignment [DELETE]
+ Response 204


# Assignment submissions [/courses/{course_id}/assignments/{ass_id}/submissions]

## Get all submissions for assignment [GET]
+ Response 200

## Create a new submission for this assignment [POST]
+ Response 201

# Assignment submission [/courses/{course_id}/assignments/{ass_id}/submissions/{sub_id}]
## Get a specific assignment submission by id [GET]
+ Response 200 (application/json)

        {
            "id": 123,
            "author": 42,
            "date": "2012-04-23T18:25:43.511Z",
            "description": "Some note to teachers"
        }

## Update existing assignment submission [PUT]
+ Response 200

## Delete existing assignment submission [DELETE]
+ Response 204

# Submission reviews [/courses/{course_id}/assignments/{ass_id}/submissions/{sub_id}/reviews]

## Get all submission reviews [GET]
+ Response 200

## Create a new submission review [POST]
+ Response 201

# Submission review [/courses/{course_id}/assignments/{ass_id}/submissions/{sub_id}/reviews/{review_id}]

## Get specific submission review [GET]
+ Response 200

## Update existing submission review [PUT]
+ Response 200

## Delete existing submission review [DELETE]
+ Response 204

# Group Course announcements

# Announcements [/courses/{course_id}/announcements]
## Get all course announcements [GET]
+ Response 200

## Create a new course announcement [POST]
+ Response 201

# Announcement [/courses/{course_id}/announcements/{announce_id}]
## Get specific course announcement [GET]
+ Response 200

## Update existing course announcement [PUT]
+ Response 200

## Delete existing course announcement [DELETE]
+ Response 204

# Group Course users

# Course users [/courses/{course_id}/users]

## Get all course users [GET]
+ Response 200

## Add user to course [POST]
+ Response 201

# Course user [/courses/{course_id}/users/{user_id}]

## Get course user [GET]
+ Response 200 (application/json)

        {
            "id": 123,
            "role": "student|teacher"
            "fullname": "Asen Lekov",
            "gitub": "L3K0V",
            "email": "asenlekoff@gmail.com",
            "details" : {
                "grade": 10,
                "class": "A",
                "number": 5
            }
        }

## Modify existing course user [PUT]
+ Response 200

## Delete existing course user [DELETE]
+ Response 200