
from os import environ

from .base import *

DEBUG = False
TEMPLATE_DEBUG = False

SECRET_KEY = environ['SECRET_KEY']

LIFEBELT_GITHUB_CLIENT_ID = environ['LIFEBELT_GITHUB_CLIENT_ID']
LIFEBELT_GITHUB_CLIENT_SECRET = environ['LIFEBELT_GITHUB_CLIENT_SECRET']

LIFEBELT_BOT_TOKEN = environ['LIFEBELT_BOT_TOKEN']

EMAIL_HOST_USER = environ['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = environ['EMAIL_HOST_PASSWORD']
